import java.util.jar.JarFile
import org.gradle.api.plugins.JavaBasePlugin

plugins {
    id 'java'
}

base.archivesName = "${mod_name}"

allprojects {
    plugins.withType(JavaBasePlugin) {
        java.toolchain.languageVersion = JavaLanguageVersion.of(8)

        project.apply plugin: 'eclipse'
        project.apply plugin: 'idea'
    }

    repositories {
        mavenLocal()
        mavenCentral()
    }

    version = "${minecraft_version}-${mod_version}"
    group = "${mod_group}"
}

configurations {
    shadow {
        canBeConsumed = false
        canBeResolved = true
    }
}

dependencies {
    shadow project(path: ':common', configuration: 'shadow')
    shadow project(path: ':bukkit', configuration: 'shadow')
    shadow project(path: ':forge', configuration: 'shadow')
}

jar {
    dependsOn(':common:shadowJar')
    dependsOn(':bukkit:jar')
    dependsOn(':forge:reobfJar')

    inputs.files(configurations.shadow.incoming.files)

    doFirst {
        from {
            configurations.shadow.incoming.files.collect { zipTree(it) }
        }
        manifest {
            attributes configurations.shadow.incoming.files.collectEntries { new JarFile(it).manifest.mainAttributes.collectEntries { k, v -> [k.toString(), v] } }
        }
    }
}
