plugins {
    id 'java'
}

base.archivesName = "${mod_name}"

allprojects {
    plugins.withType(org.gradle.api.plugins.JavaBasePlugin) {
        java.toolchain.languageVersion = JavaLanguageVersion.of(8)

        project.apply plugin: 'eclipse'
        project.apply plugin: 'idea'
    }

    repositories {
        mavenLocal()
        mavenCentral()
    }

    version = "${minecraft_version}-${mod_version}"
    group = "${mod_group}"
}

jar {
    from { zipTree(project(':common').shadowJar.archiveFile) }
    from { zipTree(project(':bukkit').jar.archiveFile) }
    from { zipTree(project(':forge').jar.archiveFile) }
}
