# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.44
forge_version=14.23.5.2860
forge_mappings_channel=stable
forge_mappings_version=39-1.12
forge_access_transformers=openterraingenerator_at.cfg
forge_plugin_class=com.pg85.otg.forge.asm.excluded.launch.OTGCorePlugin
worldedit_forge_version=6.1.6

# bukkit
bukkit_version=R0.1-SNAPSHOT
worldedit_bukkit_version=6.1.5

# mod
mod_name=OpenTerrainGenerator
mod_group=com.pg85.otg
mod_version=v9.7

# dependencies
shadow_version=9.2.2
jackson_version=2.9.7
snakeyaml_version=1.23
worldedit_core_version=6.1.4-SNAPSHOT
