plugins {
    id 'java'
    id 'com.gradleup.shadow' version "${shadow_version}"
}

base.archivesName = "${mod_name}-common"

dependencies {
    implementation "com.fasterxml.jackson.core:jackson-annotations:${jackson_version}"
    implementation "com.fasterxml.jackson.core:jackson-core:${jackson_version}"
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${jackson_version}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jackson_version}"
    implementation "org.yaml:snakeyaml:${snakeyaml_version}"
}

shadowJar {
    dependencies {
        include dependency(':jackson-annotations')
        include dependency(':jackson-core')
        include dependency(':jackson-dataformat-yaml')
        include dependency(':jackson-databind')
        include dependency(':snakeyaml')
    }
    relocate 'com.fasterxml.jackson', 'com.pg85.otg.shaded.fasterxml.jackson'
    relocate 'org.yaml', 'com.pg85.otg.shaded.org.yaml'
}

configurations {
    shadow
}

artifacts {
    shadow shadowJar.archiveFile
}
